name: tarot_fal
description: "Tarot falı uygulaması."
publish_to: 'none'

# app bundle version "7.1"
version: 1.0.0+7.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Temel
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.5


  flutter_launcher_icons: ^0.14.3


  # Arayüz
  flutter_card_swiper: ^7.0.2
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  lottie: ^3.1.1
  animated_text_kit: ^4.2.2

  # Veri İşleme
  http: ^1.2.2
  json_annotation: ^4.9.0

  # Dil ve Yapay Zeka
  flutter_dotenv: ^5.2.1
  easy_localization: ^3.0.7
  intl: 0.19.0
  google_generative_ai: ^0.4.6
  logger: ^1.3.0

  # BLOC Pattern ve State Yönetimi
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0

  share_plus: ^10.1.4

  #purchase
  in_app_purchase: ^3.2.1

  permission_handler: ^11.4.0
  audioplayers: ^6.0.0

  # Localization
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_messaging: ^15.2.4
  cloud_firestore: ^5.6.5
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4
  firebase_app_check: ^0.3.2+4

  flutter_native_splash: ^2.4.0

  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/animations/
    - assets/audios/flip_card.mp3
    - assets/audios/ritualistic3.mp3
    - assets/audios/shuffle_cards.mp3
    - assets/audios/transitional-swipe.mp3
    - assets/image_fx_c.jpg
    - assets/tarot_card_images/
    - assets/tarot_card_images/card_back.png
    - assets/tarot_card_silhouette.jpg
    - assets/tarot_cards_en.json
    - assets/tarot_cards_tr.json

  # Jenerik L10n
  generate: true
flutter_intl:
  enabled: true

flutter_launcher_icons:
  # Android ikon dosyalarının temel adı 'launcher_icon' olacak.
  # Bu, mipmap klasörlerinde launcher_icon.png dosyaları oluşturacak.
  # Önceki bildirim hatasıyla ilgili olarak, eğer bildirim ikonunu
  # @mipmap/launcher_icon olarak ayarlarsanız bu isimle eşleşir.
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_1.png"

  # İkonlar bu görselden oluşturulacak
  # adaptive_icon_background: "#2c1f4a" # İsteğe bağlı: Adaptif ikonlar için arka plan rengi
  # adaptive_icon_foreground: "assets/logo_foreground.png" # İsteğe bağlı: Adaptif ikonlar için ön plan katmanı (daha iyi sonuç verir)

flutter_native_splash:
  # Splash ekranının genel arka plan rengi
  color: "#2c1f4a"

  # Splash ekranında gösterilecek ana görsel (Android 12 öncesi ve iOS için)
  image: assets/logo_1.png

  android: true
  ios: true
  fullscreen: true # Tam ekran splash

  # --- Android < 12 Ayarları ---
  # 'fill' yerine 'center' kullanmak genellikle logonun bozulmasını önler.
  # Logo ekranın ortasında, orijinal boyutunda veya sığacak şekilde görünür.
  android_gravity: center # <-- ÖNERİLEN DEĞİŞİKLİK: 'fill' yerine 'center'

  # --- iOS Ayarları ---
  # 'scaleAspectFill' logonun bazı kısımlarını kırpabilir.
  # 'scaleAspectFit' logonun tamamını gösterir, kenarlarda boşluk kalabilir.
  # 'center' ise orijinal boyutunda ortalar. Logo tasarımınıza göre seçin.
  ios_content_mode: scaleAspectFit # <-- ÖNERİLEN DEĞİŞİKLİK: 'scaleAspectFill' yerine 'scaleAspectFit' veya 'center'

  # --- Android 12 ve Sonrası Ayarları ---
  # Bu bölüm, Android 12+ cihazlarda sistem tarafından yönetilen splash ekranını ayarlar.
  # Ortada bir ikon gösterilir, tam ekran görsel DEĞİLDİR.
  android_12:
    # Android 12 splash ekranında ORTADA görünecek ikon.
    # BURASI ÖNEMLİ: Genellikle uygulamanın launcher ikonuyla aynı olur.
    # Ancak 'logo_1.png' gibi tam bir logo görseli burada genellikle
    # iyi görünmez, sistem tarafından küçültülüp kırpılabilir.
    # İDEAL olan, özel olarak bu ekran için hazırlanmış, kenarlarında boşlukları olan
    # (adaptive icon safe zone'a uygun) bir ikon dosyası kullanmaktır.
    # Şimdilik logo_1.png kalabilir, ancak görünümünü test edin.
    # Alternatif: adaptive_icon_foreground kullanarak launcher icon oluşturduysanız onu kullanın.
    image: assets/logo_1.png # <-- TEST EDİN, gerekirse özel bir splash ikonu oluşturun (örn: assets/icons/splash_icon_android12.png)

    # Android 12'de ikonun arkasındaki dairenin veya şeklin rengi.
    icon_background_color: "#2c1f4a" # Ana renk ile uyumlu olması iyi bir başlangıç.

    # Opsiyonel Koyu Tema Ayarları (Yorumları kaldırıp değerleri ayarlayabilirsiniz)
    # color_dark: "#1a112a"
    # image_dark: assets/logo_1_dark.png # Android 12 için koyu tema ikonu
    # icon_background_color_dark: "#1a112a"

    # Opsiyonel Marka Logosu (Splash ekranının altında küçük bir logo)
    # branding: assets/branding_logo.png
    # branding_dark: assets/branding_logo_dark.png
    # branding_mode: bottom # veya center