name: tarot_fal
description: "Tarot fortune app."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8


  provider: ^6.1.2


  json_annotation: ^4.9.0
  http: ^1.2.2
  shared_preferences: ^2.3.5

  # UI Bileşenleri
  flutter_card_swiper: ^7.0.2
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1

  # Dil Desteği
  easy_localization: ^3.0.7
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  logging: ^1.3.0
  google_generative_ai: ^0.4.6
  lottie: ^3.1.1
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: 5.0.0

  json_serializable: ^6.7.1
  build_runner: ^2.4.7



flutter:


  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/animations/tarot_loading.json
    - assets/animations/tarot_shuffle.json
    - assets/tarot_card_images/
    - assets/tarot_cards.json
    - assets/animations/

