name: tarot_fal
description: "Tarot falı uygulaması."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Temel
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.5

  # Arayüz
  flutter_card_swiper: ^7.0.2
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  lottie: ^3.1.1
  animated_text_kit: ^4.2.2

  # Veri İşleme
  http: ^1.2.2
  json_annotation: ^4.9.0

  # Dil ve Yapay Zeka
  flutter_dotenv: ^5.2.1
  easy_localization: ^3.0.7
  intl: 0.19.0
  google_generative_ai: ^0.4.6
  logger: ^1.3.0

  # BLOC Pattern ve State Yönetimi
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0

  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/tarot_card_images/
    - assets/tarot_cards.json
    - .env

  # Jenerik L10n
  generate: true
flutter_intl:
  enabled: true