name: tarot_fal
description: "Tarot falı uygulaması."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Temel
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.5


  flutter_launcher_icons: ^0.14.3


  # Arayüz
  flutter_card_swiper: ^7.0.2
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  lottie: ^3.1.1
  animated_text_kit: ^4.2.2

  # Veri İşleme
  http: ^1.2.2
  json_annotation: ^4.9.0

  # Dil ve Yapay Zeka
  flutter_dotenv: ^5.2.1
  easy_localization: ^3.0.7
  intl: 0.19.0
  google_generative_ai: ^0.4.6
  logger: ^1.3.0

  # BLOC Pattern ve State Yönetimi
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0

  share_plus: ^10.1.4

  #purchase
  in_app_purchase: ^3.2.1

  permission_handler: ^11.4.0
  audioplayers: ^6.0.0

  # Localization
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_messaging: ^15.2.4
  cloud_firestore: ^5.6.5
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4
  firebase_app_check: ^0.3.2+4

  flutter_native_splash: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/animations/
    - assets/image_fx_a.jpg
    - assets/image_fx_c.jpg
    - assets/tarot_card_images/
    - assets/tarot_card_images/card_back.png
    - assets/tarot_card_silhouette.jpg
    - assets/tarot_cards_en.json
    - assets/tarot_cards_tr.json

  # Jenerik L10n
  generate: true
flutter_intl:
  enabled: true

  flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/image_fx_c.jpg"

flutter_native_splash:
  color: "6A1B9A"
  image: assets/tarot_card_silhouette.jpg
  android: true
  ios: true
  fullscreen: true

  # Görselin tüm ekrana yayılması için:
  android_gravity: fill          # Android'de resmi ekrana yayar
  ios_content_mode: scaleAspectFill # iOS'ta resmi ekrana yayar

  android_12:
    image: assets/tarot_card_silhouette.jpg
    icon_background_color: "#6A1B9AFF"
