// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'tarot_fal';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String TAROT_LOADING = 'assets/animations/tarot_loading.json';
  static const String TAROT_SHUFFLE = 'assets/animations/tarot_shuffle.json';
  static const String TAROT_CARDS = 'assets/tarot_cards.json';
}
