
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1xv2UDVzBm8wlkmp2CHwB8hWUgkR_C18',
    appId: '1:507065627600:web:a0fe1e19325b35aa893fd5',
    messagingSenderId: '507065627600',
    projectId: 'tarot-9326f',
    authDomain: 'tarot-9326f.firebaseapp.com',
    storageBucket: 'tarot-9326f.firebasestorage.app',
    measurementId: 'G-TCH47QG0XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBupKdJz_FyrDa54uAwWvLrs59enZQvQRw',
    appId: '1:507065627600:android:fd2585685c21f056893fd5',
    messagingSenderId: '507065627600',
    projectId: 'tarot-9326f',
    storageBucket: 'tarot-9326f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlcHPh1hg3VvvjdU4PFT7oesjK3sJDpo0',
    appId: '1:507065627600:ios:673e747f19b99d52893fd5',
    messagingSenderId: '507065627600',
    projectId: 'tarot-9326f',
    storageBucket: 'tarot-9326f.firebasestorage.app',
    iosBundleId: 'com.example.tarotFal',
  );
}